//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVRADAR.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVRADAR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feel like you want to make a donation?  It would be gratefully received.  Click the button to donate via GitHub sponsors..
        /// </summary>
        public static string AboutTabItem_DonationText {
            get {
                return ResourceManager.GetString("AboutTabItem_DonationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Say hello, make a feature request, or raise a bug through one of these channels:.
        /// </summary>
        public static string AboutTabItem_GetInTouchExtendedText {
            get {
                return ResourceManager.GetString("AboutTabItem_GetInTouchExtendedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string AboutTabItem_GetInTouchText {
            get {
                return ResourceManager.GetString("AboutTabItem_GetInTouchText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This project is completely open source. If you like it and want to say thanks you could hit the GitHub Star button, tweet or post about it, or tell your mum about it!.
        /// </summary>
        public static string AboutTabItem_OpenSourceExtendedText {
            get {
                return ResourceManager.GetString("AboutTabItem_OpenSourceExtendedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Source.
        /// </summary>
        public static string AboutTabItem_OpenSourceText {
            get {
                return ResourceManager.GetString("AboutTabItem_OpenSourceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XIVRADAR.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ChatCodes_SaveChangesText {
            get {
                return ResourceManager.GetString("ChatCodes_SaveChangesText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter Enabled.
        /// </summary>
        public static string FilterItem_FilterEnabledText {
            get {
                return ResourceManager.GetString("FilterItem_FilterEnabledText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MinLevel.
        /// </summary>
        public static string FilterItem_MinLevelText {
            get {
                return ResourceManager.GetString("FilterItem_MinLevelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        public static string FilterItem_RegularExpressionText {
            get {
                return ResourceManager.GetString("FilterItem_RegularExpressionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FilterItem_TypeText {
            get {
                return ResourceManager.GetString("FilterItem_TypeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compass Mode.
        /// </summary>
        public static string HomeTabItem_CompassModeText {
            get {
                return ResourceManager.GetString("HomeTabItem_CompassModeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Filter.
        /// </summary>
        public static string HomeTabItem_CreateFilterText {
            get {
                return ResourceManager.GetString("HomeTabItem_CreateFilterText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DebugInfo.
        /// </summary>
        public static string HomeTabItem_DebugInfoText {
            get {
                return ResourceManager.GetString("HomeTabItem_DebugInfoText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Filter.
        /// </summary>
        public static string HomeTabItem_DeleteFilterItemText {
            get {
                return ResourceManager.GetString("HomeTabItem_DeleteFilterItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Advanced Options.
        /// </summary>
        public static string HomeTabItem_EditFilterItemText {
            get {
                return ResourceManager.GetString("HomeTabItem_EditFilterItemText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity Filters.
        /// </summary>
        public static string HomeTabItem_EntityFiltersText {
            get {
                return ResourceManager.GetString("HomeTabItem_EntityFiltersText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Radar.
        /// </summary>
        public static string HomeTabItem_ShowRadarText {
            get {
                return ResourceManager.GetString("HomeTabItem_ShowRadarText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Transparent Radar.
        /// </summary>
        public static string HomeTabItem_ShowTransparentRadarText {
            get {
                return ResourceManager.GetString("HomeTabItem_ShowTransparentRadarText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XIVRADAR.
        /// </summary>
        public static string HomeTabItem_WelcomeText {
            get {
                return ResourceManager.GetString("HomeTabItem_WelcomeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_AboutButtonText {
            get {
                return ResourceManager.GetString("MainWindow_AboutButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string MainWindow_ChatLogButtonText {
            get {
                return ResourceManager.GetString("MainWindow_ChatLogButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string MainWindow_DebugButtonText {
            get {
                return ResourceManager.GetString("MainWindow_DebugButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainWindow_HomeButtonText {
            get {
                return ResourceManager.GetString("MainWindow_HomeButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_SettingsButtonText {
            get {
                return ResourceManager.GetString("MainWindow_SettingsButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Palette_AccentText {
            get {
                return ResourceManager.GetString("Palette_AccentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Palette_DarkText {
            get {
                return ResourceManager.GetString("Palette_DarkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Palette_LightText {
            get {
                return ResourceManager.GetString("Palette_LightText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        public static string Palette_MidText {
            get {
                return ResourceManager.GetString("Palette_MidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary - Mid.
        /// </summary>
        public static string Palette_PrimaryMidText {
            get {
                return ResourceManager.GetString("Palette_PrimaryMidText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string PaletteSelector_AccentText {
            get {
                return ResourceManager.GetString("PaletteSelector_AccentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string PaletteSelector_DarkText {
            get {
                return ResourceManager.GetString("PaletteSelector_DarkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is your current palette..
        /// </summary>
        public static string PaletteSelector_DescriptionText {
            get {
                return ResourceManager.GetString("PaletteSelector_DescriptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string PaletteSelector_LightText {
            get {
                return ResourceManager.GetString("PaletteSelector_LightText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string PaletteSelector_PrimaryText {
            get {
                return ResourceManager.GetString("PaletteSelector_PrimaryText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string RadarSettings_DistanceText {
            get {
                return ResourceManager.GetString("RadarSettings_DistanceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity Settings.
        /// </summary>
        public static string RadarSettings_EntitySettingsText {
            get {
                return ResourceManager.GetString("RadarSettings_EntitySettingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entity Type.
        /// </summary>
        public static string RadarSettings_EntityTypeText {
            get {
                return ResourceManager.GetString("RadarSettings_EntityTypeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FontColor.
        /// </summary>
        public static string RadarSettings_FontColorText {
            get {
                return ResourceManager.GetString("RadarSettings_FontColorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        public static string RadarSettings_FontSizeText {
            get {
                return ResourceManager.GetString("RadarSettings_FontSizeText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gathering.
        /// </summary>
        public static string RadarSettings_GatheringText {
            get {
                return ResourceManager.GetString("RadarSettings_GatheringText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HPP.
        /// </summary>
        public static string RadarSettings_HPPText {
            get {
                return ResourceManager.GetString("RadarSettings_HPPText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string RadarSettings_JobText {
            get {
                return ResourceManager.GetString("RadarSettings_JobText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monster A Rank.
        /// </summary>
        public static string RadarSettings_MonsterARankText {
            get {
                return ResourceManager.GetString("RadarSettings_MonsterARankText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monster B Rank.
        /// </summary>
        public static string RadarSettings_MonsterBRankText {
            get {
                return ResourceManager.GetString("RadarSettings_MonsterBRankText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monster S Rank.
        /// </summary>
        public static string RadarSettings_MonsterSRankText {
            get {
                return ResourceManager.GetString("RadarSettings_MonsterSRankText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        public static string RadarSettings_MonsterText {
            get {
                return ResourceManager.GetString("RadarSettings_MonsterText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RadarSettings_NameText {
            get {
                return ResourceManager.GetString("RadarSettings_NameText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NPC.
        /// </summary>
        public static string RadarSettings_NPCText {
            get {
                return ResourceManager.GetString("RadarSettings_NPCText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string RadarSettings_OtherText {
            get {
                return ResourceManager.GetString("RadarSettings_OtherText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string RadarSettings_PCText {
            get {
                return ResourceManager.GetString("RadarSettings_PCText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string RadarSettings_ShowText {
            get {
                return ResourceManager.GetString("RadarSettings_ShowText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chat Codes.
        /// </summary>
        public static string SettingsTabItem_ChatCodesTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_ChatCodesTabHeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string SettingsTabItem_RadarText {
            get {
                return ResourceManager.GetString("SettingsTabItem_RadarText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharlayan.
        /// </summary>
        public static string SettingsTabItem_SharlayanTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_SharlayanTabHeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTabItem_ThemeTabHeaderText {
            get {
                return ResourceManager.GetString("SettingsTabItem_ThemeTabHeaderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string UserSettings_ActionsHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ActionsHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string UserSettings_ActorHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ActorHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adjust these timings to increase or decrease data latency. Faster timings may increase CPU usage..
        /// </summary>
        public static string UserSettings_AdjustmentText {
            get {
                return ResourceManager.GetString("UserSettings_AdjustmentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string UserSettings_ChatLogHelperText {
            get {
                return ResourceManager.GetString("UserSettings_ChatLogHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Player.
        /// </summary>
        public static string UserSettings_CurrentPlayerHelperText {
            get {
                return ResourceManager.GetString("UserSettings_CurrentPlayerHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Settings.
        /// </summary>
        public static string UserSettings_DataSettingsText {
            get {
                return ResourceManager.GetString("UserSettings_DataSettingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string UserSettings_InventoryHelperText {
            get {
                return ResourceManager.GetString("UserSettings_InventoryHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job Resources.
        /// </summary>
        public static string UserSettings_JobResourcesHelperText {
            get {
                return ResourceManager.GetString("UserSettings_JobResourcesHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Timings.
        /// </summary>
        public static string UserSettings_MemoryTimingsText {
            get {
                return ResourceManager.GetString("UserSettings_MemoryTimingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Party Members.
        /// </summary>
        public static string UserSettings_PartyMembersHelperText {
            get {
                return ResourceManager.GetString("UserSettings_PartyMembersHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string UserSettings_ResetSettingsText {
            get {
                return ResourceManager.GetString("UserSettings_ResetSettingsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string UserSettings_TargetHelperText {
            get {
                return ResourceManager.GetString("UserSettings_TargetHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use locally cached JSON for Sharlayan resources.
        /// </summary>
        public static string UserSettings_UseCachedDataText {
            get {
                return ResourceManager.GetString("UserSettings_UseCachedDataText", resourceCulture);
            }
        }
    }
}
